services:
  db:
    image: postgres
    restart: no
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: 123
    networks:
      - afisha

  adminer:
    image: adminer
    restart: no
    ports:
      - 8084:8080
    networks:
      - afisha

  afisha.web:
    image: ${DOCKER_REGISTRY-}afishaweb
    build:
      context: .
      dockerfile: src/Afisha.Web/Dockerfile
    restart: no
    ports:
      - '8080:8080'
      - '8081:8081'
    depends_on: 
      - db
    networks:
      - afisha

volumes:
    pgdata:
        external: true
networks:
  afisha:
