---
# Postgres Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "123"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata-pvc

---
# Postgres Service
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: NodePort

---
# Adminer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        ports:
        - containerPort: 8080

---
# Adminer Service
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  selector:
    app: adminer
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8080
  type: NodePort

---
# Afisha Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: afisha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: afisha
  template:
    metadata:
      labels:
        app: afisha
    spec:
      containers:
      - name: afisha
        image: ghcr.io/scrummaster123/afisha_otus:latest
        ports:
        - containerPort: 8080
        - containerPort: 8081
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z db-service 5432; do echo waiting for db; sleep 2; done;']

---
# Afisha Service
apiVersion: v1
kind: Service
metadata:
  name: afisha-service
spec:
  selector:
    app: afisha
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: NodePort
---
# PersistentVolumeClaim for pgdata
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed
