# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: no
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - '5432:5432'
    volumes:
      - 'C:\Work\Docker\Shared\PGSQL\data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: 123

  adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080