name: CI-CD

on:
  push:
    branches:
      - docker
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker-compose build 
          docker tag kuberdeploytest:latest ghcr.io/${{ github.repository_owner }}/afisha_otus:latest
          docker push ghcr.io/${{ github.repository_owner }}/afisha_otus:latest

  deploy-to-docker:
    runs-on: clonx  # Must run on a machine with Docker installed
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Docker
        run: |
          docker-compose up -d


